### PR TITLE
Add analyzer.py.

### PR DESCRIPTION
**Pull request by progval**

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
Absolutely awesome.

**Comment by progval** [comment]
wait

**Comment by RaitoBezarius** [comment]
Alright, let me know whenever I can merge it.

**Comment by jilljenn** [comment]
Are you guys using GitHub comments for chatting? :P I receive a notification every time.

**Comment by RaitoBezarius** [comment]
Sorry :D. I will invite him on Slack or something like that.

**Comment by progval** [comment]
All good!

Just in case Wikipedia changes its layout and breaks the script, here are the files:

[cities.txt](https://github.com/jilljenn/voyageavecmoi/files/34854/cities.txt)
[stations.json.txt](https://github.com/jilljenn/voyageavecmoi/files/34856/stations.json.txt)

**Pull request merged**
